#!/bin/bash
if ! (pgrep -f 'transmission'|grep -q .); then
     (transmission-gtk --minimized &>/dev/null </dev/null &)
fi
"${HOME}/PythonEnvs/transmissionrpc-env/bin/python" "${HOME}/bin/transmission_prioritizace.py"
exit
